### PR TITLE
Add Gaia MAW MIST magnitudes

### PR DESCRIPTION
**Pull request by segasai**
Hi, Timothy,

MIST isochrones for Gaia now have magnitudes using the updated sensitivity curves from 1808.02820 (called Gaia_G_MAW,... )
This patch allows them to be accessed through isochrones.

     Sergey

### CODE REVIEW

**Comment by timothydmorton** [comment]
Thanks for this!  Does this work?  Do you mind adding a test somewhere initializing an isochrone with these bands? e.g.,
```python
mist = get_ichrone('mist', bands=['Gaia_G_MAW', 'Gaia_BP_MAWf', 'Gaia_BP_MAWb', 'Gaia_RP_MAW'])
mist.initialize()
```

**Comment by timothydmorton** [comment]
Great, thanks!  Will merge when passes.

**Comment by timothydmorton** [comment]
And just to make sure I understand the context here; these are recalibrated bandpasses that should be *better* than the default/originals, right?  Is it maybe worth making these the default when users ask for gaia bandpasses?  What do you think?

**Comment by segasai** [comment]
Yes, those those should be better AFAIU https://arxiv.org/pdf/1808.02820.pdf . I haven't done any indepedent validation myself though. I wouldn't make those bands default now though.

**Comment by timothydmorton** [comment]
Great, thanks for the insight!

**Pull request merged**
